//ruta src/app/(public)/layout.tsx
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function PublicLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    // Ya no usamos <html> ni <body> aquí, usamos un div contenedor[cite: 4]
    <div className="min-h-full flex flex-col">
      {children}
    </div>
  );
}